### PR TITLE
fix(ios): preserving EXIF data

### PR DESCRIPTION
**Pull request by codeconsole**
Incorporates the changes done by @ryaa that enable EXIF information to be retained on selected image.

https://github.com/apache/cordova-plugin-camera/commits/master/src/ios/CDVCamera.m

@ryaa: Enabled preserving exif data
Change to prevent saving the image file twice
Added authorization/permission request for camera roll
Added the fix to correctly handle iOS 14 new Photos picker permissions

@karlvr Fix background thread calling UI APIs

### CODE REVIEW

**Comment by codeconsole** [comment]
PING: @jukka @shazron @infil00p @jlongster   Please fix this plugin by either merging or coming up with you own solution.  This plugin has been broken for years as is and does not work according to its documentation.   Being such an important plugin, having this one broken is killing the cordova community.

**Comment by erisu** [comment]
@codeconsole Can you explain how you are testing the PR changes?

When I took a photo using the changes from #712, the GPS Exif data does not exist.

JavaScript Sample:

```js
const cameraOptions = {
  quality: 100,
  destinationType: Camera.DestinationType.FILE_URI,
  sourceType: Camera.PictureSourceType.CAMERA,
  encodingType: Camera.EncodingType.JPEG,
  mediaType: Camera.MediaType.PICTURE,
  saveToPhotoAlbum: true,
}

cameraTakePhoto.onclick = function() {
  navigator.camera.getPicture(onPhotoDataSuccess, onFail, cameraOptions);
};
```

config.xml Sample
```xml
<platform name="ios">
    <preference name="CameraUsesGeolocation" value="true" />

    <edit-config target="NSCameraUsageDescription" file="*-Info.plist" mode="merge">
        <string>need camera access to take pictures</string>
    </edit-config>

    <edit-config target="NSPhotoLibraryUsageDescription" file="*-Info.plist" mode="merge">
        <string>need photo library access to get pictures from there</string>
    </edit-config>

    <edit-config target="NSLocationWhenInUseUsageDescription" file="*-Info.plist" mode="merge">
        <string>need location access to find things nearby</string>
    </edit-config>

    <edit-config target="NSPhotoLibraryAddUsageDescription" file="*-Info.plist" mode="merge">
        <string>need photo library access to save pictures there</string>
    </edit-config>
</platform>
```

From iOS's "Photo" app, I selected the photos from the gallery and airdropped them to my macOS. I opened the JPG photos with the "Previewer" app and opened the "Show Inspector" > "More Info" tab > "Exif" sub-tab. In this tab, there is no GPS location data.

From iOS's "Photo" app, I also tried checking by the "Places" category, and it's not there.

After taking the photo and clicking on the "Select" button, the location permission request dialog did open. I tried both options, "Allow Once" and "Allow While Using App" but neither of them made a difference.

There was also a minor issue that I noticed while testing. The location permission dialog will automatically close itself after a few seconds. This does not give people enough time to read and confirm. The dialog should not close until the user responds.

**Comment by codeconsole** [comment]
@erisu These are just @ryaa 's iOS changes from here https://github.com/apache/cordova-plugin-camera/issues/759 .  I believe all it fixes is just the exif information when a photo is selected from the Photos library.

**Comment by codeconsole** [comment]
@erisu I've had this working on a released app for months. I can confirm that it fixes the issue of exif information being stored on photos chose from the photo library.

**Review by erisu — APPROVED** [review]
- app builds
- photos can be taken
- can fetch photos from gallery

**Pull request merged**
