### PR TITLE
Show caption text over the camera - android only

### PR DESCRIPTION
**Pull request by ijajmulani**
### Platforms affected
Android

### What does this PR do?
Show caption text over the camera 

### Checklist
- [ ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by ijajmulani** [comment]
Here is the attached photo of text over the camera

**Comment by infil00p** [comment]
There are far better ways to accomplish this instead of using Toasts.  There has been zero discussion over adding this feature on the lists, so I'm going to close this PR.

**Comment by ijajmulani** [comment]
Hi @infil00p ,
Sorry for not discussing this feature. I am beginner in open source contribution can you tell me where to iscuss this feature so we can implement.

**Comment by ijajmulani** [comment]
HI @infil00p Created issue over here https://issues.apache.org/jira/browse/CB-13993

**Pull request closed without merging**
