### PR TITLE
major bugs when user picture

### PR DESCRIPTION
**Pull request by roysG**
I got from play store three different bugs that user got on their side when they used camera.

I will write the bugs and the devices:

1.
Device: LG Spirit LTE (c70) / android v5.0

Bug:
java.lang.RuntimeException: Unable to resume activity {com.pick.tags/com.pick.tags.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=49, result=-1, data=Intent { dat=file:///storage/emulated/0/Android/data/com.pick.tags/cache/.Pic.jpg (has extras) }} to activity {com.pick.tags/com.pick.tags.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2976)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3007)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2373)
	at android.app.ActivityThread.access$800(ActivityThread.java:149)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=49, result=-1, data=Intent { dat=file:///storage/emulated/0/Android/data/com.pick.tags/cache/.Pic.jpg (has extras) }} to activity {com.pick.tags/com.pick.tags.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3581)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2962)
	... 11 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
	at org.apache.cordova.camera.CameraLauncher.failPicture(CameraLauncher.java:1067)
	at org.apache.cordova.camera.CameraLauncher.processPicture(CameraLauncher.java:1056)
	at org.apache.cordova.camera.CameraLauncher.processResultFromGallery(CameraLauncher.java:594)
	at org.apache.cordova.camera.CameraLauncher.onActivityResult(CameraLauncher.java:695)
	at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:120)
	at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:353)
	at android.app.Activity.dispatchActivityResult(Activity.java:6222)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3577)

2.
Device:
LG Spirit LTE (c70) / android v5.0
Bug:
java.lang.RuntimeException: Unable to resume activity {com.pick.tags/com.pick.tags.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=49, result=-1, data=Intent { dat=content://media/external/images/media/4243 }} to activity {com.pick.tags/com.pick.tags.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2976)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3007)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2373)
	at android.app.ActivityThread.access$800(ActivityThread.java:149)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=49, result=-1, data=Intent { dat=content://media/external/images/media/4243 }} to activity {com.pick.tags/com.pick.tags.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3581)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2962)
	... 11 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
	at org.apache.cordova.camera.CameraLauncher.failPicture(CameraLauncher.java:1067)
	at org.apache.cordova.camera.CameraLauncher.processPicture(CameraLauncher.java:1056)
	at org.apache.cordova.camera.CameraLauncher.processResultFromGallery(CameraLauncher.java:594)
	at org.apache.cordova.camera.CameraLauncher.onActivityResult(CameraLauncher.java:695)
	at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:120)
	at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:353)
	at android.app.Activity.dispatchActivityResult(Activity.java:6222)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3577)

Device:  LG G3 (g3) / android v5.0

Bugs:

java.lang.RuntimeException: Unable to resume activity {com.pick.tags/com.pick.tags.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=49, result=0, data=null} to activity {com.pick.tags/com.pick.tags.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2958)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2989)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2372)
	at android.app.ActivityThread.access$800(ActivityThread.java:148)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5274)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=49, result=0, data=null} to activity {com.pick.tags/com.pick.tags.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3556)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2944)
	... 11 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
	at org.apache.cordova.camera.CameraLauncher.failPicture(CameraLauncher.java:1067)
	at org.apache.cordova.camera.CameraLauncher.onActivityResult(CameraLauncher.java:698)
	at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:120)
	at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:353)
	at android.app.Activity.dispatchActivityResult(Activity.java:6179)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3552)

Please assist, Thanks.

### CODE REVIEW

**Comment by nikhilkh** [comment]
This PR seems to be incorrect. We have a fix for this issue already committed and will release in the next cordova-android & camera plugin release.

**Comment by riknoll** [comment]
@nikhilkh is right; the issue you are referencing is [CB-9189](https://issues.apache.org/jira/browse/CB-9189). There was a fix for that merged recently and I wrote about how to use it in the comments [here](https://issues.apache.org/jira/browse/CB-10309). Hope that helps!

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully. 

**Dashboard** - http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6/

**Results**
1. [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=windows-slave,platformName=windows-8.1-store/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=windows-slave,platformName=windows-8.1-store/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=windows-slave,platformName=windows-8.1-store/testReport/) - [Device Logs]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=windows-slave,platformName=windows-8.1-store/artifact/)
2. [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=windows-slave,platformName=windows-10-store/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=windows-slave,platformName=windows-10-store/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=windows-slave,platformName=windows-10-store/testReport/) - [Device Logs]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=windows-slave,platformName=windows-10-store/artifact/)
3. [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=windows-slave,platformName=windows-8.1-phone/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=windows-slave,platformName=windows-8.1-phone/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=windows-slave,platformName=windows-8.1-phone/testReport/) - [Device Logs]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=windows-slave,platformName=windows-8.1-phone/artifact/)
4. [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=mac-slave,platformName=ios/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=mac-slave,platformName=ios/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=mac-slave,platformName=ios/testReport/) - [Build Artifacts]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=mac-slave,platformName=ios/artifact/)
5. [Android Mac]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=mac-slave,platformName=android/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=mac-slave,platformName=android/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=mac-slave,platformName=android/testReport/) - [Build Artifacts]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=mac-slave,platformName=android/artifact/)
6. [Android Windows]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=windows-slave,platformName=android/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=windows-slave,platformName=android/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=windows-slave,platformName=android/testReport/) - [Device Logs]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/6//label=windows-slave,platformName=android/artifact/)

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-camera/pull/147/commits/0115458ce8c0ab3476ddf5f2bf4ba3d5452965cb)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=windows-slave,platformName=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=windows-slave,platformName=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=windows-slave,platformName=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=windows-slave,platformName=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=windows-slave,platformName=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=windows-slave,platformName=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=windows-slave,platformName=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=windows-slave,platformName=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=windows-slave,platformName=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=windows-slave,platformName=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=windows-slave,platformName=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=windows-slave,platformName=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=mac-slave,platformName=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=mac-slave,platformName=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=mac-slave,platformName=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=mac-slave,platformName=ios/artifact/) |
| [Android Mac]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=mac-slave,platformName=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=mac-slave,platformName=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=mac-slave,platformName=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=mac-slave,platformName=android/artifact/) |
| [Android Windows]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=windows-slave,platformName=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=windows-slave,platformName=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=windows-slave,platformName=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/11//label=windows-slave,platformName=android/artifact/) |

**Pull request closed without merging**
