### PR TITLE
fixed bug. Photo editor

### PR DESCRIPTION
**Pull request by lounai-chen**
### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by lounai-chen** [comment]
fixed bug. Photo editor

**Comment by lounai-chen** [comment]
fixed bug. Photo editor

**Comment by lounai-chen** [comment]
fixed bug. Photo editor

**Comment by breautek** [comment]
Is there an open issue for the bug? Which bug is this fixing?

**Comment by breautek** [comment]
The submitted code is taken from [Capacitor](https://github.com/ionic-team/capacitor-plugins/blob/main/camera/android/src/main/java/com/capacitorjs/plugins/camera/ExifWrapper.java).

The offending files are
- CameraResultType
- CameraSettings
- CameraSource
- ExitWrapper
- ImageUtils

You did not disclose the fact that this code originally belongs to and is copyrighted by Ionic. I also do not believe you have the legal authority to submit this code on the behalf of Ionic.

**Pull request closed without merging**
