### PR TITLE
feat(android)!: Android 13 support

### LINKED ISSUE #825: Support for Android api 33
# Feature Request

## Motivation Behind Feature

READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE used in CameraLauncher.java from API 33 are no longer available.
Instead, fine-grained permission controls such as READ_MEDIA_IMAGES are required.

https://developer.android.com/about/versions/13/behavior-changes-13

## Feature Description

READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE always return denied, so these need to be corrected.

### PR DESCRIPTION
**Pull request by erisu**
### Platforms affected

android

### Motivation and Context

Android 13 Support

### Description

- Rebase of #814
- Simplified the `getPermissions` method.

closes #814
resolves #825

### Testing

- npm t
- built test app

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Review by breautek — APPROVED** [review]
untested, but code-wise lgtm

**Comment by christiaan** [comment]
I am trying to use this together with the cordova-plugin-file.

Both the plugins write an entry concerning the WRITE_EXTERNAL_STORAGE to the manifest.
And I guess because it is now conditional I end up with two lines like the following.

```
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:maxSdkVersion="32" android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

Which causes the following error

> Error:
        Element uses-permission#android.permission.WRITE_EXTERNAL_STORAGE at AndroidManifest.xml:50:5-108 duplicated with element declared at AndroidManifest.xml:49:5-81

Is this something I should fix in my project?

**Comment by erisu** [comment]
I believe this would be something you fix within your project.

`cordova-plugin-file` version 8.0.0 has removed permission `WRITE_EXTERNAL_STORAGE`.

If you are using a plugin that depends on `cordova-plugin-file` make sure it is requesting for version 8.0.0. 

If it is not, check if there is a new plugin version that hopefully supports `cordova-plugin-file` 8.0.0.

Note: Some Cordova core plugins depend on the file plugin and not updated, but it is in the process of being updated.

If you are adding the `cordova-plugin-file` directly and it is not a depedency of another plugin, it might be OK to bump its version.

**Comment by christiaan** [comment]
> If you are adding the `cordova-plugin-file` directly and it is not a depedency of another plugin, it might be OK to bump its version.

That is exactly how I fixed it :smile: and seeing the original PR already mentioning this issue I removed the question.

**Comment by christiaan** [comment]
On an Android 8.0 device it fails after it asks for permission the first time with the following error

```
FATAL EXCEPTION: main
Process: com.myapp.app, PID: 22690
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.myapp.app/com.myapp.app.MainActivity}: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=22690, uid=10176 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4491)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
    at android.app.ActivityThread.-wrap20(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6944)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=22690, uid=10176 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
    at android.os.Parcel.readException(Parcel.java:1967)
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
    at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
    at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
    at android.content.ContentResolver.query(ContentResolver.java:760)
    at android.content.ContentResolver.query(ContentResolver.java:710)
    at android.content.ContentResolver.query(ContentResolver.java:668)
    at org.apache.cordova.camera.CameraLauncher.queryImgDB(CameraLauncher.java:1222)
    at org.apache.cordova.camera.CameraLauncher.takePicture(CameraLauncher.java:325)
    at org.apache.cordova.camera.CameraLauncher.onRequestPermissionResult(CameraLauncher.java:1362)
    at org.apache.cordova.CordovaInterfaceImpl.onRequestPermissionResult(CordovaInterfaceImpl.java:222)
    at org.apache.cordova.CordovaActivity.onRequestPermissionsResult(CordovaActivity.java:527)
    at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7780)
    at android.app.Activity.dispatchActivityResult(Activity.java:7603)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534) 
    at android.app.ActivityThread.-wrap20(Unknown Source:0) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752) 
    at android.os.Handler.dispatchMessage(Handler.java:105) 
    at android.os.Looper.loop(Looper.java:164) 
    at android.app.ActivityThread.main(ActivityThread.java:6944) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```

If I then choose to pick a picture using using `Camera.PictureSourceType.PHOTOLIBRARY` it requests permission for storage and after that the `Camera.PictureSourceType.CAMERA` also works again.

I am calling `getPicture` like so
```
navigator.camera.getPicture(this.onCameraSuccess.bind(this), this.onCameraError.bind(this), {
    quality: 50,
    destinationType: Camera.DestinationType.DATA_URL,
    sourceType: Camera.PictureSourceType.CAMERA,
    allowEdit: false,
    encodingType: Camera.EncodingType.JPEG,
    correctOrientation: true,
    targetWidth: 1024,
    targetHeight: 1024
});
```

**Review by okanbeydanol — APPROVED** [review]

**Comment by erisu** [comment]
@christiaan I updated the PR to fix the Android 8.0 and lower issue you reported. Can you confirm if it resolved for you?

**Comment by christiaan** [comment]
> @christiaan I updated the PR to fix the Android 8.0 and lower issue you reported. Can you confirm if it resolved for you?

@erisu I can confirm the last commit resolved the issue on Android 8.0 (Samsung A3 2017) :+1:  thanks!

**Review by christiaan — APPROVED** [review]

**Comment by breautek** [comment]
> untested, but code-wise lgtm

Just an update, I tested this PR against my app and it seems good to go, at least in my usage of the camera plugin.

**Comment by michelsondan** [comment]
Thank you, now camera working on android 13

**Comment by EinfachHans** [comment]
Looks like `7.0.0` is not published on npm, can someone please do this?

**Pull request merged**
