### PR TITLE
CB-10120 android: Camera permission must be requested when present in Manifest

### PR DESCRIPTION
**Pull request by riknoll**
Because three PRs are better than one.

This provides fixes for #142 and is based on top of the rebase in #174 

I will merge this in soon

### CODE REVIEW

**Comment by riknoll** [comment]
@MatthewBooth I want to merge this in. Have you filed an ICLA? See the prerequisites here: http://cordova.apache.org/contribute/contribute_guidelines.html

**Comment by okonon** [comment]
@riknoll there are multiple PRs related to this issue. @MatthewBooth can you please fill out needed documentation?

**Comment by okonon** [comment]
@riknoll what in particular the ICLA for this PR? For the fact that @MatthewBooth rebased someone else's commits? If yes, can someone more responsive create a new PR and fill out ICLA for that?

**Comment by riknoll** [comment]
There were conflicts that he resolved, so yes I do need an ICLA

**Comment by okonon** [comment]
@riknoll got it thanks a lot. Fingers crossed. hopefully he will do it soon

**Comment by MatthewBooth** [comment]
ICLA was filled out. Sorry for the delay, I hadn't been tracking these comments unfortunately. It's done now, though.

**Comment by riknoll** [comment]
I will merge this today, need to resolve some merge conflicts. Thanks @MatthewBooth!

**Comment by MatthewBooth** [comment]
@ochakov mainly! :D

**Comment by riknoll** [comment]
Right, thanks @ochakov as well!

**Comment by riknoll** [comment]
Alright, I resolved the conflicts but after looking at the code I want to do another round of testing before I merge this in. This will be the first thing on my plate tomorrow, thanks for being patient!

**Pull request closed without merging**
