### PR TITLE
CB-12873: Add customization options for caputre button, resizing of v…

### PR DESCRIPTION
**Pull request by charlesverge**
…ideo browser resize

Reported issue https://issues.apache.org/jira/browse/CB-12873

### Platforms affected

browser platform

### What does this PR do?

The browser version of the camera plugin is missing

    Adds options to configure
        class name for div which holds video preview
        Option to disable audio
    Adds Cancel button
    Resizing of video upon browser resize or orientation change
    Graceful activation of file selector dialog and visibility of file input

### What testing has been done on this change?

Tested on chrome and firefox

### Checklist
- [x ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [X ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-camera/pull/268/commits/4c09f37c680fa6bb076ed526766145a53fc0d10a)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/169/)

 140 tests run, 0 skipped, 0 failed.

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-camera/pull/268/commits/6667c4f527a29d2bb588e447b4b75ad78edbe2e8)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/170/)

 316 tests run, 28 skipped, 0 failed.

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-camera/pull/268/commits/8c02fe49b9a812dd90ee58d9defc99784daac7cd)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/171/)

 316 tests run, 28 skipped, 1 failed.

**Comment by alsorokin** [comment]
cordova-qa: rerun tests

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-camera/pull/268/commits/8c02fe49b9a812dd90ee58d9defc99784daac7cd)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/172/)

 316 tests run, 28 skipped, 0 failed.

**Comment by charlesverge** [comment]
Added a check to prevent error from null value being passed

**Comment by jadurani** [comment]
Any update on this?

**Comment by janpio** [comment]
@charlesverge Are you still around and could rebase this to resolve the conflict?

**Comment by charlesverge** [comment]
@janpio @jadurani I've rebased this.

And I have a test cordova app to demo how to use the options at
https://github.com/charlesverge/cordova-camera-test

With the key pieces in
https://github.com/charlesverge/cordova-camera-test/blob/master/www/js/index.js
https://github.com/charlesverge/cordova-camera-test/blob/master/www/css/index.css

**Comment by janpio** [comment]
Awesome, thank you @charlesverge !

Travis has some comments (test failures):

```
/Users/travis/build/apache/cordova-plugin-camera/src/browser/CameraProxy.js
   90:51  error  Infix operators must be spaced             space-infix-ops
  100:47  error  Infix operators must be spaced             space-infix-ops
  106:30  error  Strings must use singlequote               quotes
  112:29  error  Strings must use singlequote               quotes
  118:53  error  Infix operators must be spaced             space-infix-ops
  131:52  error  Infix operators must be spaced             space-infix-ops
  151:26  error  Missing space before function parentheses  space-before-function-paren
  160:29  error  Strings must use singlequote               quotes
  161:30  error  Strings must use singlequote               quotes
  170:27  error  Missing space before function parentheses  space-before-function-paren
  183:36  error  Strings must use singlequote               quotes
  184:36  error  Strings must use singlequote               quotes
  230:33  error  Strings must use singlequote               quotes
  231:33  error  Strings must use singlequote               quotes
```

**Comment by janpio** [comment]
Hey, I just fixed the problem that caused Android tests to fail in `master`. Could you rebase this PR please? This should get rid of the Android failures and possibly fix all test failures for this PR.

**Comment by charlesverge** [comment]
@janpio I've rebased the commit, the changes since the last rebase do not affect this code and everything looks good.

**Pull request closed without merging**
