### PR TITLE
fix(camera): resultForVideo uri in iOS13

### LINKED ISSUE #506: iOS13 file_uri error picking video from gallery
# Bug Report

## Problem
In iOS 13, picking video from Roll returns a bad FILE_URI no proprietary (only affected picking video, no photo)

### What is expected to happen?
Return a valid proprietary FILE_URI url to work with it (for upload to server, for example)
like: file:///var/mobile/Containers/Data/Application/98D7C3AE-A24F-46CE-A3B4-CF03B26355BE/tmp/video.mp4

### What does actually happen?
Returns a invalid non proprietary FILE_URI with no access to work with, like:
file:///private/var/mobile/Containers/Data/PluginKitPlugin/43792FA5-A8F8-4ECA-8CCE-0C5877088858/tmp/trim.7F9B8FC4-3307-4452-9F96-46A5D9A9DDD5.MOV

## Information
Using any iOS device, like iPhone upgraded to iOS 13, try to pick a video (no photo) and then load the FILE_URI returned by plugin. If you'll try to use this FILE_URI to any action, like upload the file to server for example, the log in xcode says "Error opening file. Error Domain=NSCocoaErrorDomain Code=257. You are not allowed to read this file."
** Note: This function works correctly before upgrade to iOS13. I've tried it to many iOS devices with the same result.

### Command or Code

var options = {
    destinationType: 1,
    sourceType : 0,
    mediaType: 1
};
navigator.camera.getPicture(correcto, fail, options);

### Environment, Platform, Device
MacOS Mojave, using Xcode 11 and iPhone Xs upgraded to iOS 13

### Version information
Cordova 9, Camera Plugin upgraded today
MacOS Mojave, using Xcode 11 and iPhone Xs upgraded to iOS 13

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

### PR DESCRIPTION
**Pull request by guillem-sopra**
In iOS 13, videos' uris are not being retrieved properly as this issue describes: https://github.com/apache/cordova-plugin-camera/issues/506#issue-496782771

Closes #506 

### Platforms affected

iOS

### Motivation and Context

This PR aims to solve that bug ir order for the plugin to retrieve the file's uri properly. Full credit for this solution to https://github.com/apache/cordova-plugin-camera/issues/506#issuecomment-534070130.

### Description
Please see https://github.com/apache/cordova-plugin-camera/issues/506#issue-496782771

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by AdrianCastello** [comment]
image

**Comment by breautek** [comment]
Can you edit the PR to include one of the keywords that signals that this issue closes #506 

Github is bit picky, you must be explicit "fixes <issueTag>" for example.

https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by guillem-sopra** [comment]
Done 👍

**Comment by fvadouko** [comment]
Please,

How to use this PR in my package. json like : git+https://github.com/apache/cordova-plugin-inappbrowser.git#27fe8ec8d4db84b34700d32c1f1351c9189cb951 ?

**Comment by guillem-sopra** [comment]
> Can you edit the PR to include one of the keywords that signals that this issue closes #506
> 
> Github is bit picky, you must be explicit "fixes #issueTag" for example.
> 
> https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

Hey @breautek am I missing anything else?

**Comment by breautek** [comment]
@guillem-sopra I'm not very experienced in the ios codebase, nor do I have apple hardware to test so I'm unable to make a code review.

**Comment by fvadouko** [comment]
How to use this PR in my package. json like : git+https://github.com/apache/cordova-plugin-inappbrowser.git#27fe8ec8d4db84b34700d32c1f1351c9189cb951 ?

Because, i use ionic cordova to build one of my app to iOS

**Comment by guillem-sopra** [comment]
> @guillem-sopra I'm not very experienced in the ios codebase, nor do I have apple hardware to test so I'm unable to make a code review.

😢  How do you usually proceed in cases like this, then? Is there anybody I can 'enforce' to code-review/test this PR?

**Comment by breautek** [comment]
> > @guillem-sopra I'm not very experienced in the ios codebase, nor do I have apple hardware to test so I'm unable to make a code review.
> 
>  How do you usually proceed in cases like this? Is there anybody I can 'enforce' to code-review/test this PR?

Cordova is entirely volunteer driven so I can't "force" anybody to do a PR.

**Comment by fvadouko** [comment]
Anybody to help, please ?

i use ionic cordova to build one of my app to iOS, and the last release not working - no video can upload to my server. And this fix could solve my issue.

Anybody to help, please ? 
Or How to use this PR in my package. json like : git+https://github.com/apache/cordova-plugin-inappbrowser.git#27fe8ec8d4db84b34700d32c1f1351c9189cb951 ?

Please !

**Comment by rricamar** [comment]
Hi, any update on this? Ty for any feedback in advance 🙏 😞

**Comment by fvadouko** [comment]
Hey,

when will you deliver a new release with this PR ? I, myself, wait for it, for my ionic app.

**Comment by rayelward** [comment]
@fvadouko 
> Anybody to help, please ?
> Or How to use this PR in my package. json like : git+https://github.com/apache/cordova-plugin-inappbrowser.git#27fe8ec8d4db84b34700d32c1f1351c9189cb951 ?
> 
> Please !

`"cordova-plugin-camera": "git+https://github.com/apache/cordova-plugin-camera.git#4cc795c118af8f97f1cfd1076370be01fce00e71"` 
in my package dependencies is working for me right now to target this specific commit. I'll keep following this PR to see when its released and I can switch back to the master versioned releases... hopefully sometime before iOS 14 comes and breaks something else.

**Comment by RHinderiks** [comment]
When will this be merged and released?

**Comment by onatcipli** [comment]
#506 @fvadouko you can add a cordova plugin from github repository with the following command

```
cordova plugin add github_url
```

for example:
I just forked the repo from @guillem-sopra _(thank you for the PR)_ then I added a fixed plugin from github repository

```
cordova plugin add https://github.com/onatcipli/cordova-plugin-camera/tree/fix/camera-result-for-video-url
```

**Comment by wingo7** [comment]
Does this work for you, guys? Because I still have a path with trim fragments and after closing, the app video file is not available

**Comment by rricamar** [comment]
Hi @wingo7 , if you read the whole original issue, you'll see that in addition of the plugin source code solution, you'll need also to patch the fileUri after the plugin call:

```typescript
fileUri = await this.camera.getPicture(options);

// XXX: fix path for file:// protocol in iOS 13
const indexOfFilePrefix = parseInt(fileUri.indexOf('file://'), 10);

if (indexOfFilePrefix === -1) {
    fileUri = `file://${fileUri}`;
}
```

I hope this help you 👍

**Comment by wingo7** [comment]
@rricamar the problem was in the other, I've changed code in the wrong place, after changing code by path: 'projectName/platforms/ios/projectName/Plugins/cordova-plugin-camera/CDVCamera.m' it works for me, thanks for replying me.
Hope, my answer help the others, who faced with it

**Comment by rricamar** [comment]
As long as I know @guillem-sopra is not working anymore on his previous company, so don't expect any changes on this PR

**Comment by guillem-sopra** [comment]
Look @jcesarmobile man, this is sad. I created this PR 5 moths ago, coming form an issue that went unattended for long (with lots of comments of users asking to be fixed and released). I didicated also hours form my spare time to get the code, test it and create the PR (crediting the original poster). I am not an Objective-C nor Cordova plugin developer, I just wanted to help. Now, 5 moths later, you request changes, which seem to be really simple to implement to an experienced Objective-C developer. As I said, I am not that, nor I have the project's code or the needed devices to test. 

I know OSS is frustrating, it relies on developers' good will and people sometimes can be rought with their demands. But I think this is not the case: this issue was absolutely abandonded. IMHO, not attending the issue with the level of activity it had for 5 months can't be considered mantaining a project. If anyone does not have the proper time to do it, its totally undestandable, but it should remove himself from the project. If nobody can, then the project must be marked as unmaintained or deprecated. 

I am going to try to do my best to implement the changes requested, but man, publicly complaining on twitter, ommitting that the issue was ignored for moths (a key point in this situation), all by a thumbs downreaction ... not fair.

**Comment by rricamar** [comment]
OK, I've just tried last commit of the PR and it works, for test it:

``` bash
cordova plugin rm cordova-plugin-camera
cordova plugin add git+https://github.com/guillem-sopra/cordova-plugin-camera\#7e28e1d3456d7f12591983d7c5a70fe9cab2a40c
```

Tested on an iPad Mini (iOS 13.3.1)

Pls @jcesarmobile check it out again since maybe your request changes won't allow merge, ty 👍

**Comment by rricamar** [comment]
Hey @jcesarmobile I saw bfa38fed2c9141d614ebbbe5786f3904f7a90202, does it mean this PR  is no longer needed? Hope it gets released soon, ty 👍

**Comment by indraraj26** [comment]
any update on this issue?

**Comment by mwyld** [comment]
This issue knocked me out for hours. When will it be merged?

**Comment by jcesarmobile** [comment]
this problem is not present on 5.0.0

**Comment by wingo7** [comment]
@jcesarmobile Thanks, but it doesn't work as expected for ios 14.1, WKWebView mode only, for cordova-ios 4.5.0, or cordova-ios 5.1.1. The problem is that I can't see the image or video after restarting the app. 
error in console:
Failed to load resource: (file path here) The requested URL was not found on this server.

**Comment by PegasusAwesome** [comment]
> this problem is not present on 5.0.0
Jus tested this with 5.0.0, and this problem was still very much present.

In 5.0.0 we still see an invalid non proprietary FILE_URI with no access to work with, like:
file:///private/var/mobile/Containers/Data/PluginKitPlugin/4D7CFBAC-1D1E-4CCD-8F79-5C0E3FC0E2C8/tmp/trim.F82BBDFE-D013-4122-942D-45459045E3A5.MOV

**Pull request closed without merging**
