### PR TITLE
Adding force orientation lock to Camera 

### PR DESCRIPTION
**Pull request by weaponhax**
Hi,
Sorry if this is the wrong way to ask for features,

But I do hope this feature is going to be implemented soon. 

i.e choosing/forcing what orientation the camera should shoot in, either portrait or landscape or both.

Is there an alternative workable solution?

Thankyou and keep up the good work.

Hax

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully. 

**Dashboard** - http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5/

**Results**
1. [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=windows-slave,platformName=windows-8.1-store/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=windows-slave,platformName=windows-8.1-store/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=windows-slave,platformName=windows-8.1-store/testReport/) - [Device Logs]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=windows-slave,platformName=windows-8.1-store/artifact/)
2. [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=windows-slave,platformName=windows-10-store/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=windows-slave,platformName=windows-10-store/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=windows-slave,platformName=windows-10-store/testReport/) - [Device Logs]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=windows-slave,platformName=windows-10-store/artifact/)
3. [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=windows-slave,platformName=windows-8.1-phone/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=windows-slave,platformName=windows-8.1-phone/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=windows-slave,platformName=windows-8.1-phone/testReport/) - [Device Logs]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=windows-slave,platformName=windows-8.1-phone/artifact/)
4. [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=mac-slave,platformName=ios/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=mac-slave,platformName=ios/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=mac-slave,platformName=ios/testReport/) - [Build Artifacts]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=mac-slave,platformName=ios/artifact/)
5. [Android Mac]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=mac-slave,platformName=android/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=mac-slave,platformName=android/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=mac-slave,platformName=android/testReport/) - [Build Artifacts]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=mac-slave,platformName=android/artifact/)
6. [Android Windows]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=windows-slave,platformName=android/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=windows-slave,platformName=android/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=windows-slave,platformName=android/testReport/) - [Device Logs]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/5//label=windows-slave,platformName=android/artifact/)

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-camera/pull/167/commits/0115458ce8c0ab3476ddf5f2bf4ba3d5452965cb)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=windows-slave,platformName=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=windows-slave,platformName=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=windows-slave,platformName=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=windows-slave,platformName=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=windows-slave,platformName=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=windows-slave,platformName=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=windows-slave,platformName=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=windows-slave,platformName=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=windows-slave,platformName=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=windows-slave,platformName=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=windows-slave,platformName=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=windows-slave,platformName=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=mac-slave,platformName=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=mac-slave,platformName=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=mac-slave,platformName=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=mac-slave,platformName=ios/artifact/) |
| [Android Mac]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=mac-slave,platformName=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=mac-slave,platformName=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=mac-slave,platformName=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=mac-slave,platformName=android/artifact/) |
| [Android Windows]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=windows-slave,platformName=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=windows-slave,platformName=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=windows-slave,platformName=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/10//label=windows-slave,platformName=android/artifact/) |

**Comment by gitlovenotwar** [comment]
👍 for locking orientation of camera

**Comment by jsanchezgarcia** [comment]
I'm trying to find this feature documented somewhere, but cannot find it. Any pointers on how to use it? (for example, how can I lock the camera in landscape mode?). thanks

**Comment by LebToki** [comment]
if if the orientation of the phone is Vertical ,
we should be able to force a landscape/horizontal target file or object.

**Comment by Abhishek134** [comment]
Can anyone able to lock the camera rotation? then, please  let us know.

**Comment by Tioecomp** [comment]
I cant find this feature too, anyone?

**Comment by msd117** [comment]
I don't think we have this feature in the plugin... Please correct me if am  wrong 

I am also looking to lock the orientation to portrait mode  as I have my app locked in portrait mode 
But opening the camera is messing things up and broking my UI

**Pull request closed without merging**
