### PR TITLE
CB-10113 - Browser - Camera on top of all!

### PR DESCRIPTION
**Pull request by aliokan**
add CSS style {position: 'relative', z-index: 99999} on DOM appended element

### CODE REVIEW

**Comment by aliokan** [comment]
I have signed Apache Individual Contributor License Agreement :) 
https://people.apache.org/committer-index.html#unlistedclas Laurent Deketelaere

**Comment by riknoll** [comment]
@aliokan Thanks for doing that! Does this have a corresponding JIRA issue? Also, is there a reason you chose not to use the maximum value for the z-index? We recently merged in a similar fix for windows (see [here](https://github.com/apache/cordova-plugin-camera/pull/140))

**Comment by aliokan** [comment]
@riknoll I create a JIRA issue and change patch name and increase z-index value.

**Comment by shprink** [comment]
+1 for this

**Comment by TimBarham** [comment]
Thanks for this @aliokan. I've tweaked the commit a bit to store the magic number in a constant, and I'll merge it.

**Pull request closed without merging**
