### PR TITLE
CB-8940 Setting z-index values to maximum for UI buttons

### PR DESCRIPTION
**Pull request by rakatyal**

### CODE REVIEW

**Comment by purplecabbage** [comment]
Why 2147483646 ?

**Comment by rakatyal** [comment]
I believe that is to keep the video element behind the buttons.

**Comment by dblotsky** [comment]
You could place the value into a constant named `HIGHEST_POSSIBLE_Z_INDEX`, and then it would be both documented and easier to maintain.

**Comment by rakatyal** [comment]
Good suggestion.

**Comment by riknoll** [comment]
Agree with above. Otherwise, LGTM. Tested on an 8.1 device (and by tested I mean I took a picture, not really sure what else to do here). I don't really see how this can mess anything up.

**Pull request closed without merging**
