### PR TITLE
feat(browser): Give video and button tags an id attribute

### PR DESCRIPTION
**Pull request by Clementp57**
Allows developer to style both video and button tags in Browser.

### CODE REVIEW

**Comment by riknoll** [comment]
Does this have a corresponding [JIRA](https://issues.apache.org/jira/secure/Dashboard.jspa) issue? Also, I don't see your name in the [ICLA list](https://people.apache.org/committer-index.html); could you please [submit an ICLA](http://www.apache.org/licenses/#clas)?

**Comment by riknoll** [comment]
@Clementp57 any updates?

**Comment by janpio** [comment]
Hey @Clementp57 , there seems to be a merge conflict now. Could you maybe fix this? Thanks.

**Comment by jcesarmobile** [comment]
closing since the conflicts have not been fixed after a year

**Pull request closed without merging**
