### PR TITLE
[iOS] Fixed how checks access authorization to camera & library

### PR DESCRIPTION
**Pull request by m-revetria**

### CODE REVIEW

**Comment by riknoll** [comment]
Thanks for making this into a PR! The JIRA is here: [CB-10128](https://issues.apache.org/jira/browse/CB-10128)

@m-revetria, I don't se your name in [the ICLA list](https://people.apache.org/committer-index.html#unlistedclas). You need to submit one before this is eligible to be merged in. Instructions for doing so are [here](http://cordova.apache.org/contribute/contribute_guidelines.html).

**Comment by m-revetria** [comment]
I just sent ICLA signed by email, I'll let you know when I have response from secretary@apache.org

**Comment by riknoll** [comment]
@m-revetria Thanks!

**Comment by m-revetria** [comment]
@riknoll Hi, just to let you know that my signed ICLA has been filed in the Apache Software Foundation records.

**Comment by riknoll** [comment]
Thanks @m-revetria! @vladimir-kotikov when you get the chance, would you mind reviewing this?

**Comment by vladimir-kotikov** [comment]
LGTM

**Comment by omefire** [comment]
LGTM!

**Pull request closed without merging**
