### PR TITLE
[CB-10388] - Added correctOrientation support for android 4.4

### PR DESCRIPTION
**Pull request by horozco**
Jira issue: https://issues.apache.org/jira/browse/CB-10388
- Currently If You pass the correctOrientation param as true, the sourceType as PHOTOLIBRARY or SAVEDPHOTOALBUM, the media type as ALLMEDIA and the selected file is an image the correctOrientation function is not being called. Also even if the function is called the code is not detecting the URI and doesn’t rotate the picture. These changes fixed both issues.

### CODE REVIEW

**Comment by riknoll** [comment]
Thanks for submitting a PR! The ALLMEDIA thing definitely sounds like a bug and your change there looks good.

However, I'm not 100% sure about the changes you made to `getImageOrientation()`. The issue is that when we get an image URI, it may or may not map to an actual file location depending on the application that provided the URI. For example, Google Photos can provide URIs that point to images in the cloud and not on the physical device. In this case, using the content resolver is the correct method for getting the orientation because the content resolver knows how to handle those situations. Thoughts?

**Comment by fmiboy** [comment]
Hello guys,
Currently I have image orientation correct when I use PNG type and on Android 4.4.4 but Android 5 orientation doesn't work at all.
Any idea when there will be fix?

Thanks

**Comment by morioma** [comment]
I prefer this one to https://github.com/apache/cordova-plugin-camera/pull/197, because that one has code duplication for calculating rotation.
I am thinking getting rid of the ```getImageOrientation``` function all together and use the ```getRotatedBitmap``` from ```processResultFromCamera``` which based on the EXIF helper.

Additionally, the issue may not just for android 4.4. Latest Android 6.0.1 on a Galaxy S6 edge suffers the same issue.

**Comment by swbradshaw** [comment]
@morioma  - Take a look at #197 again. I completely rewrote the implementation.

**Comment by infil00p** [comment]
Closing this since #197 got merged in

**Pull request closed without merging**
