### PR TITLE
CB-12593: (android) move management of FileProvider out of the camera plugin

### PR DESCRIPTION
**Pull request by cjpearson**
### Platforms affected

Android

### What does this PR do?

It allows multiple plugins to use the FileProvider. Each plugin that needs a provider path can add it using the config-file element. Another plugin will update the AndroidManifest and create the provider_paths file.

I've created a stub for this other plugin at https://github.com/cjpearson/cordova-plugin-file-provider so it builds correctly. I'm not sure if this other plugin should be a new plugin or added to an existing plugin.

### What testing has been done on this change?

Tested locally with cordova-android 6.1.2.

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully.

**Commit**     - [Link](https://github.com/apache/cordova-plugin-camera/pull/257/commits/bfb150efea8297406f06c12a1e0631b4ffae91f8)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148//PLATFORM=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148//PLATFORM=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148//PLATFORM=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148//PLATFORM=windows-10-store/artifact/) |
| [iOS 9.3]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148//PLATFORM=ios-9.3/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148//PLATFORM=ios-9.3/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148//PLATFORM=ios-9.3/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148//PLATFORM=ios-9.3/artifact/) |
| [iOS 10.0]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148//PLATFORM=ios-10.0/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148//PLATFORM=ios-10.0/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148//PLATFORM=ios-10.0/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148//PLATFORM=ios-10.0/artifact/) |
| [Android]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148//PLATFORM=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148//PLATFORM=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148//PLATFORM=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera-pr/148//PLATFORM=android/artifact/) |

**Comment by cjpearson** [comment]
@stevengill could you take a look at this PR? Thanks!

**Comment by filmaj** [comment]
I'm not sure we can merge this PR in as it relies on a non-Apache plugin. We would have to move that file provider plugin under the Cordova umbrella. Thoughts @stevengill ?

**Comment by infil00p** [comment]
I can't find the issue in JIRA. At any rate, I don't think we should pull this in right now, and I think that we should probably move this into the android platform source in the future.  Is there a specific use case that needs this plugin currently?

**Comment by cjpearson** [comment]
Thanks for the feedback. I agree that it should go under the cordova umbrella somewhere. I just wanted to show a working example in the PR.

We have an internal plugin in our project that also uses the FileProvider and a provider_paths file. Attempting to upgrade the camera plugin to 2.3.1 fails the build with a duplicate element error. The only work around is to define both paths in one of the plugins which makes them dependent on each other and means we have to maintain a modified version of the camera plugin.

Sorry, I messed up the title. The JIRA issue is [here](https://issues.apache.org/jira/browse/CB-12593).

**Comment by infil00p** [comment]
@cjpearson After reading this, I can see this issue appearing even if we do move the management into cordova-android.  This is a tooling issue that we're going to have to handle.

**Comment by cjpearson** [comment]
@infil00p, I'm not very familiar with the internals of cordova-android. What do you mean by a tooling issue?

**Comment by cjpearson** [comment]
I think https://github.com/apache/cordova-plugin-camera/pull/274 may be a better solution. Closing.

**Pull request closed without merging**
