### PR TITLE
[Android] fix: support lollipop and earlier android versions to return a file path from uri regardless of file type.

### PR DESCRIPTION
**Pull request by SecuriTeam**
I've only tested this on Android versions:
LG Optimus L3 II - 4.1.1 - API 16
Samsung Galaxy S3 - 4.2.2 - API 17
HTC Evo - 4.3 - API 18
Nexus 4 - 5.0.0 - API 21
on Genymotion emulator.
and Galaxy Note 3 - 5.0.0 - API 21 on my actual phone.

### CODE REVIEW

**Comment by devpaul** [comment]
Hi, I was wondering if this was going to be reviewed soon. I'm receiving content uris for some media types on a Nexus 5 - 5.1 and I am hoping this could help resolve the issue.

**Comment by infil00p** [comment]
Does this have a corresponding JIRA issue? Also, I'm going to talk about this on the dev list before pulling it in.

**Comment by vladimir-kotikov** [comment]
@infil00p, is there any updates on this?

**Comment by infil00p** [comment]
I've added a smaller fix in the Marshmallow camera to provide a real path, but it doesn't work with remote files.  We're not accepting this code in the repository without an ICLA or a CCLA, depending in how big SecuriTeam is.

**Pull request closed without merging**
