### PR TITLE
(ios) Add: Flash mode option to control Flash light of Camera

### PR DESCRIPTION
**Pull request by quangpdt**
### Platforms affected

- iOS

### Motivation and Context

We are developing app the allow user to take pictures of such object as car chassis and even in the dark places. In such case, it turns out the flash light should be switched on by default and users won't have to do it manually (The default setting of Flash mode is `UIImagePickerControllerCameraFlashModeAuto`)

### Description
- This implementation is only affected for iOS platform
- Add new enum called `FlashMode` with 3 values: `AUTO`, `ON`, `OFF`. The value of each property is based on the value from enum `UIImagePickerControllerCameraFlashMode`:
	```objective-c
	typedef NS_ENUM(NSInteger, UIImagePickerControllerCameraFlashMode) {
	    UIImagePickerControllerCameraFlashModeOff  = -1,
	    UIImagePickerControllerCameraFlashModeAuto = 0,
	    UIImagePickerControllerCameraFlashModeOn   = 1
	} __TVOS_PROHIBITED;
	```
- Add new option to `camera.CameraOptions` called `flashMode` with default value is `Camera.FlashMode.AUTO`.

### Testing
- Manual tested already on our applications.

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)(https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Comment by janpio** [comment]
Can this feature later be implemented on other platforms as well or is this an iOS thing?

**Comment by quangpdt** [comment]
@janpio : I would like to do the same thing with Android platform. But with limited knowledge and capacity (My team is only working on iOS platform), I'm not able to do that at the moment

**Comment by DungHoangNVG** [comment]
Much appreciated if anyone could follow up this effort but for Android platform 👍

**Comment by loet** [comment]
Great feature, very much awaited!

**Comment by quangpdt** [comment]
@erisu: Could you please take a look to my PR?

**Comment by quangpdt** [comment]
@timbru31: Any chance for merging this PR? It has been 1 month and no action at all :(

**Review by erisu — CHANGES_REQUESTED** [review]
There is a lot of changes that has nothing to do with this PR goal and should be reverted/removed before the PR can be merged.

**Comment by quangpdt** [comment]
> There is a lot of changes that has nothing to do with this PR goal and should be reverted/removed before the PR can be merged.

Never mind, I created this PR on 3rd May, **2019**, and NO action at all.  And now on Aug 2021, you said there're a lot of conflicts. Sorry but just a joke to me

**Pull request closed without merging**
