### PR TITLE
CB-13264 (iOS): Remove ios usage descriptions

### PR DESCRIPTION
**Pull request by jcesarmobile**
### Platforms affected
iOS

### What does this PR do?
Removes the usage description variables and document how to set them using edit-config tab

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by kleeb** [comment]
its not working in Phonegap Build

**Comment by jcesarmobile** [comment]
This just removes the usage description variables from the plugin.xml, so not sure how this "is not working in Phonegap build".

Anyway, this is not the place to report your Phonegap build problems

**Comment by kleeb** [comment]
thats true, but there is no way to add those params to the plist file with the latest update of PGB
which more or less makes the cordova-plugin-camera version stuck at 2.4.1...

unless using cordova-plugin-ios-camera-permissions

**Comment by jcesarmobile** [comment]
Yes, there is a way, you have to use `edit-config` tag as documented in the README.md

**Comment by kleeb** [comment]
edit-config doesn't work in the Phonegap Build version cli-7.1.0

**Comment by kleeb** [comment]
just stating that thousands of PGB users will soon have problem when they update this plugin

**Comment by jcesarmobile** [comment]
edit-config used to work in PGB. If it's now broken in cli-7.1.0 report it to Adobe, this plugin is from Apache.

**Comment by jcesarmobile** [comment]
@kleeb FYI, I've created a sample app and built it in PGB setting the cli-7.1.0 and the texts were set correctly. You can try it yourself https://github.com/jcesarmobile/cordova-plugin-camera-sample.

First time I built it without version and was built with 6.5.0 and didn't include the texts but then I changed the CLI version, built it again and worked fine.

**Comment by kleeb** [comment]
Thanks @jcesarmobile 
For this repo it works like charm

For my project it doesn't, some other plugin must be removing them.

**Comment by kleeb** [comment]
Ok, we are using the old builder, and then it is not working

<preference name='pgb-builder-version' value='1' />

**Comment by jcesarmobile** [comment]
If you want to use the old builder then you will need to use older versions of the plugins.
Anyway, if you have doubts or problems with Phonegap Build you should go to their forums https://forums.adobe.com/community/phonegap/build

**Comment by kleeb** [comment]
I don't agree with that. This is just the different way how PGB is building the native package.
I don't see any connection with the plugin versions.

**Comment by jcesarmobile** [comment]
To use latest version of the plugins you need to use `edit-config` tag, period.

If Phonegap Build old builder doesn't allow to use `edit-config` tag you have a few options:

1. Use the new builder.
2. Use an older version of the plugin where `edit-config` tag is not need.
3. Use another plugin that writes the usage descriptions.

Anyway, I have told you a few times that this plugins belongs to Apache and Phonegap Build belongs to Adobe, they have to adapt to our changes, not the other way around. And in this case they already provide a way, so it's you who has to switch to that or find a workaround.

Please, stop commenting here.

**Pull request closed without merging**
