### PR TITLE
Rebased ochakov's branch to the latest as of writing

### PR DESCRIPTION
**Pull request by MatthewBooth**

### CODE REVIEW

**Comment by MatthewBooth** [comment]
This is in response to @infil00p's comments here: https://github.com/apache/cordova-plugin-camera/pull/142#issuecomment-186300094

I've tested in my project and this works as expected, both file permissions and camera permissions are requested and fufilled as necessary. Good work @ochakov.

I honestly don't know the codebase that well so you guys will want to check it, but it looks legit, and builds fine.

**Comment by riknoll** [comment]
This needs to use the new PermissionHelper class instead of the CordovaInterface methods for requestPermission and hasPermission

**Comment by MatthewBooth** [comment]
Probably why Travis is failing. Beyond me, though. I prefer native Java to this.

**Comment by jcesarmobile** [comment]
There was an issue on JIRA about the camera permission and was closed as "won't fix" becase camera permission shouldn't be asked by the app as we use an intent and according to the docs, it isn't needed. I don't remember the issue number right now.

**Comment by jcesarmobile** [comment]
After reading the conversation on https://github.com/apache/cordova-plugin-camera/pull/142 this makes sense.

@riknoll if the PermissionHelper class should be used instead of the cordova methods, then I assume the documentation here is wrong https://cordova.apache.org/docs/en/latest/guide/platforms/android/plugin.html#android-permissions-cordova-android-5.0.x-and-greater

**Comment by riknoll** [comment]
@jcesarmobile PermissionHelper is just for the core plugins and is a temporary measure.  See this thread: http://markmail.org/message/bwhpuh7m6fyf5eem

The Travis test has been failing for a bit (I'm pretty sure that this PR is not causing it)

**Comment by riknoll** [comment]
I also had some other comments on the old PR on the use of constants in the calls to requestPermission that didn't make it in. @MatthewBooth can you take a look? If not, I can do the fixes and add a commit. Once those changes are in I can test this PR and see about merging if everything checks out.

**Comment by riknoll** [comment]
Alright, I pushed an update branch here: https://github.com/MSOpenTech/cordova-plugin-camera/tree/CB-10120. I still need to do some testing.

**Comment by riknoll** [comment]
I'm going to merge my branch tomorrow. @MatthewBooth can you close this PR and I'll open another?

**Comment by riknoll** [comment]
Rebased and updated in #179

**Comment by riknoll** [comment]
@MatthewBooth can you fill out an ICLA? I need that in order to merge your rebase. Instructions are here: http://cordova.apache.org/contribute/contribute_guidelines.html

**Comment by MatthewBooth** [comment]
@riknoll Cheers, I've done that. Sent the ICLA signed with my GPG keys to the secretary, and signed up to JIRA.

I only rebased @ochakov's work, though, so there is no original code of mine in this. So feel free to merge with his permissions :)

**Comment by MatthewBooth** [comment]
```Dear Matt Booth, 

This message acknowledges receipt of your ICLA, which has been filed in the Apache Software Foundation records. 

If you have been invited as a committer, please advise the project PMC that your ICLA has been filed. 

Warm Regards, 

-- Craig L Russell 
Secretary, Apache Software Foundation ```

**Pull request closed without merging**
