### PR TITLE
fix(android): Declare CAMERA permission

### PR DESCRIPTION
**Pull request by breautek**
### Platforms affected
Android

### Motivation and Context

Fixes https://github.com/apache/cordova-plugin-camera/issues/471

Fixes permission issue on Android.

Camera permission is generally only required if you're using the Camera APIs, which we don't however there are a few exceptions to this rule.

As of Android M, if you try to request the `CAMERA` permission without declaring it in the manifest, a security error is thrown. See the [Note](https://developer.android.com/reference/android/provider/MediaStore.html#ACTION_IMAGE_CAPTURE) in the android documentation.

The camera plugin does request the `CAMERA` permission to handle an edge case where another plugin may include it in the manifest.

https://github.com/apache/cordova-plugin-camera/blob/5ae56cf8f07bcdfa090d928e7af3c8637521afce/src/android/CameraLauncher.java#L249-L251

### Description

Adds `<uses-permission android:name="android.permission.CAMERA" />` to `plugin.xml`

### Testing

- Ran `npm test`.
- Tested on one of my production apps.

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Review by erisu — APPROVED** [review]
I am OK with adding the permission.

**Review by NiklasMerz — APPROVED** [review]

**Comment by breautek** [comment]
The failed tes in travis is caused by unrelated platforms, so merging.

Thanks for the reviews.

**Comment by jcesarmobile** [comment]
The plugin is supposed to request the permission only if the permission is present, if that's not working properly it should be fixed instead of adding the permission. 
If we are adding the permission then the code that checks if the permissions is present should be removed because it will always be present, but I think we should revert this, I don't think it's not good to add unneeded permissions.

**Comment by breautek** [comment]
I can revisit this and try to determine why it was required for the camera permission to be declared in my app. My original conclusion was based on my own experience and several other reports that declaring the permission was necessary.

**Comment by jcesarmobile** [comment]
In the issue linked people talk about <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />, they removed it somehow and had to add it, it’s supposed to be added by the plugin but some had hooks that removed it.
One user ask if camera permission is missing and another one says adding camera permission didn’t fix their problems.

**Comment by breautek** [comment]
> In the issue linked people talk about , they removed it somehow and had to add it, it’s supposed to be added by the plugin but some had hooks that removed it.
> One user ask if camera permission is missing and another one says adding camera permission didn’t fix their problems.

Yes, and it looks like in my case it's my app to blame here. I had a deeper look and it looks like the app is using a permissions plugin to explicitly request the camera permission (then failing because the permission is not declared in the manifest). In reality, my app shouldn't even need to request camera permissions.

I'll prepare a revert PR.

**Pull request merged**
