### PR TITLE
fix(android): Fix launching camera when targeting SDK 30

### LINKED ISSUE #673: Can't open camera on Android 11 with targetSdkVersion=30
# Bug Report

### What is expected to happen?

The camera can be opened normally on Android 11 when building with `targetSdkVersion=30`.

### What does actually happen?

```
Error: You don't have a default camera.  Your device may not be CTS complaint.
```

## Information

The error comes from here: https://github.com/apache/cordova-plugin-camera/blob/0333d001c7c2df5418c2a344e275d3b43d99f2d8/src/android/CameraLauncher.java#L305

When removing the condition, the camera launches as expected.

Our current workaround is to stay on `targetSdkVersion=29`.

### Command or Code

```
camera.getPicture(onSuccess, onError, {
    quality: 50,
    destinationType: Camera.DestinationType.FILE_URI,
    sourceType: Camera.PictureSourceType.CAMERA,
    encodingType: Camera.EncodingType.JPEG,
    mediaType: Camera.MediaType.PICTURE,
    allowEdit: false,
    correctOrientation: true,
    targetWidth: 1920,
});
```

### Environment, Platform, Device

Android 11

### Version information

cordova 10.0.0
cordova-android 9.0.0
cordova-plugin-camera 5.0.0
cordova-plugin-androidx-adapter 1.1.1

```
<preference name="android-minSdkVersion" value="22" />
<preference name="android-targetSdkVersion" value="30" />
<preference name="AndroidXEnabled" value="true" />
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

### PR DESCRIPTION
**Pull request by OJ7**
### Platforms affected
Android

### Motivation and Context

Fixes #673

The Android 11 (API Level 30) migration has some changes regarding package visibility. [This page](https://developer.android.com/training/package-visibility/use-cases) mentions:

> When your app targets Android 11 or higher and uses an intent to start an activity in another app, the most straightforward approach is to invoke the intent and handle the ActivityNotFoundException exception if no app is available.

Currently, this  plugin tries to resole the intent by querying the Package Manager, seemingly for a workaround for Nexus 7. 

### Description

This PR attempts to start the activity and handle the ActivityNotFoundException error (if thrown). 

### Testing

I ran `npm test`
I tested this on an Android 11 device with an app targeting SDK 30 and it launched the camera fine. 
I haven't tested this on Nexus 7, but I did also test on a device with no camera app installed (disabled via ADB) and the error was handled gracefully.

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [X] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [X] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by OJ7** [comment]
This PR is related to #684, as both aim to address issues with SDK 30 in different ways.

This one attempts to invoke the intent (and handle error if no activity found), whereas the other PR continues using the package manager and updates the package visibility to include the `IMAGE_CAPTURE` intent in the `AndroidManifest.xml` to allow launching the camera.

**Comment by KevinCornelison-fas** [comment]
This fix solved my issue on my Moto 8 / 4GB / Android 11.  Thank you very much.
My question is, Is there a reason why this has not been merged into master? 
Is there some concern about this change?
@erisu Do you or anyone on your team have an issue with this change?

Kevin Cornelison

**Review by yogeshingale1 — APPROVED** [review]

**Review by rimakhal — APPROVED** [review]

**Comment by rimakhal** [comment]
I need it in Arabic language please

في الأحد، 12 ديسمبر 2021 8:51 ص yogeshingale1 ***@***.***>
كتب:

**Comment by yogeshingale1** [comment]
I my case when I set sdktarget 29 then camera  working but when set 30 then not 
with android@9.0.0

**Comment by erisu** [comment]
Closed by #684

The current release contains #684 which resolved the issues with Android SDK 30.

Thank you for your PR.

**Pull request closed without merging**
