### PR TITLE
(Android) Merge old PR, apply brief mods and update for Android 13

### PR DESCRIPTION
**Pull request by zubus**
### Platforms affected
Android

### Motivation and Context

**Based on https://github.com/jalios/cordova-plugin-camera/commit/bd1dd6a742bafc63591169eb371e39ad63007d97 and https://github.com/dongourdet/cordova-plugin-camera/commit/fa9570399b11af0547fd4ed77892f4c35d383d33**

https://github.com/apache/cordova-plugin-camera/issues/679
https://github.com/apache/cordova-plugin-camera/issues/660
https://github.com/apache/cordova-plugin-camera/issues/656
#825
#611 
https://github.com/apache/cordova-plugin-camera/issues/783
Closes https://github.com/apache/cordova-plugin-camera/issues/679
Closes https://github.com/apache/cordova-plugin-camera/issues/660
Closes https://github.com/apache/cordova-plugin-camera/issues/679

### Description

This Pull Request updates the previous implementation which aimed to catch RecoverableSecurityException and request permission to delete media from the Media Store. These updates ensure compatibility with the current codebase of the plugin.

In addition to revising the previous implementation, brief modifications were made to extend support for Android 13. These changes have been tested to confirm they are working as expected.

This update aligns the plugin with Android's latest standards, improving its overall reliability and usability across different Android versions.
Please, let me know if any changes or additional information are required as we move forward with this Pull Request.

### Testing

Motorola with Android 10

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [x ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by EYALIN** [comment]
@zubus thank you for your help.
it is not compiling because "getimage" is being called with 3 parameters in 2 places instead 2. can you fix it, please?

**Comment by Nikilu** [comment]
Hi All,
When it is expected to merge? Because our app is depended on this merge request so that we can fix the Camera issue for Error code '20'. Unfortunately we cannot use the fork because of some internal policy hence we need the master version.

**Comment by erisu** [comment]
I am not sure if this PR is valid anymore compared with the current release but they should:

1. Rebase the PR. There are conflicts and appears that all of these changes already exist in the current release in some form.
2. Update the description to explain exactly what the changes are remaining after the rebase and what it is resolving.

**Comment by erisu** [comment]
I would also suggest submitting each fix as its own PR. IMO usually a massive PR that fixes many things are ignored.

As the current description and title sounds primarily as a collection of changes for various things.

**Comment by breautek** [comment]
Closing as obsolete, #907 removes the code that requires `RecoverySecurityException` handling.

Several other PRs landed that better improved support for scoped storage.

**Pull request closed without merging**
