### PR TITLE
added allowEdit support for android

### PR DESCRIPTION
**Pull request by riyazMuhammad**
## Changes
1. Allows user to crop selected image from gallery or captured from camera if **allowEdit** is set to **true**
2. Fallback if device does not support **com.android.camera.action.CROP**

### CODE REVIEW

**Comment by roysG** [comment]
there is still problem with cropping in android, when  choose to capture image.
I can׳t crop, why ?

**Comment by fguerin** [comment]
Same as @roysG, I'm not able to edit the captured image.

**Comment by jsappme** [comment]
Same as @roysG, I'm not able to edit the captured image. I have a Nexus 4.

**Comment by jcesarmobile** [comment]
Read the quirks

Android Quirks
Android also uses the Crop Activity for allowEdit, even though crop should work and actually pass the cropped image back to Cordova, the only one that works consistently is the one bundled with the Google Plus Photos application. Other crops may not work.

So, you have any app that can crop like google plus photos? in case you have it, does it open?

**Pull request closed without merging**
