### PR TITLE
CB-5479 android: changed saveToPhotoAlbum to save uncompressed images

### PR DESCRIPTION
**Pull request by riknoll**
It was apparently decided a while back (CB-5749) that we should be saving the uncompressed image with `saveToPhotoAlbum` rather than the modified image when the camera options `quality`, `targetHeight`, `targetWidth`, etc. are given. iOS supports this behavior, but Android does not. This pull request changes the Android code so that when `saveToPhotoAlbum` is specified, the uncompressed image is saved to the album and the modified image is saved to the application's cache (and that URI is what is returned to the application). This also makes it so that DATA_URL actually saves images to the gallery when the flag is enabled (this was previously not the case). This might be a breaking change for some applications that relied on the old behavior (saving one image rather than two).

### CODE REVIEW

**Comment by riknoll** [comment]
@infil00p This might be breaking (sorta). What is the protocol we usually follow for merging breaking changes in?

**Comment by riknoll** [comment]
Oh, [according to this](http://callback.markmail.org/search/?q=+saveToPhotoAlbum+list%3Aorg.apache.incubator.callback-dev#query:saveToPhotoAlbum%20list%3Aorg.apache.incubator.callback-dev%20date%3A201312%20+page:1+mid:v6gqvpfabvtja6lu+state:results) we should save the cropped image if `allowEdit` is on. I'll update the PR.

**Comment by riknoll** [comment]
The commit I just pushed handles cropped images. I believe it also fixes an undocumented bug where requesting uncompressed/unedited images caused the app to ignore the crop Activity's output. That is, the user would get to crop the image and then the plugin would ignore that and just return the uncropped file.

**Comment by riknoll** [comment]
I think this should also fix CB-6640

**Comment by StopSine** [comment]
+1

**Comment by riknoll** [comment]
@infil00p, if you have no objections, I'm going to merge this in. I don't think it'll break too many people and it fixes several quirks.

**Comment by infil00p** [comment]
Sounds good.

**Comment by luofan189** [comment]
Is this issue only fixed on Android side? I am seeing the same issue on iOS with the latest release as well.

**Comment by riknoll** [comment]
@luofan189 What issue are you seeing? I can take a look.

**Comment by luofan189** [comment]
@riknoll only the low resolution image is saved on iOS device as well. I set the targetWidth and targetHeight to 1024x768

**Comment by riknoll** [comment]
@luofan189 I'll try and reproduce this. If you don't mind, let's move this conversation to the JIRA issue:

https://issues.apache.org/jira/browse/CB-5479

**Comment by riknoll** [comment]
@luofan189 I would also appreciate it if you could post the camera options you are passing to the plugin and the versions of iOS and the plugin you're using. Thanks!

**Comment by luofan189** [comment]
I have added options to that JIRA issue, @riknoll

**Pull request merged**
