### PR TITLE
[android] allowedit: fix not Cropping after taking picture from camera

### PR DESCRIPTION
**Pull request by pluswave**

### CODE REVIEW

**Comment by pluswave** [comment]
for allowedit option, the imageUrl inside processResultFromCamera is wrong (always get the original image), and sourcePath is not used. So this patch fix the issue.

**Comment by Anu2g** [comment]
This pull request worked fantastically for my team. Thanks!

**Comment by hgehlhausen** [comment]
####Hey
  Did this get merged in yet?

**Comment by pluswave** [comment]
Just checked the master branch, it seems that the issue is fixed by dca8bd1943449b201f73f860d45b28ab84676074 , so this pull request is no longer needed.

**Pull request closed without merging**
