### PR TITLE
Fix for the problem when Exif data is lost when getting an image from the photo library (iOS)

### PR DESCRIPTION
**Pull request by ryaa**
## Platforms affected
iOS

### Motivation and Context

https://github.com/apache/cordova-plugin-camera/issues/524

### Description

Added handling EXIF details for the image opened from camera roll + added some changes to make the plugin work on iOS 13

### Testing

Test on real iPhone 6S Plus with iOS 13 and simulator iPhone 7S Plus with iOS 12.2 (both taking a picture and adding an image from camera roll)

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by DavidWiesner** [comment]
Here is my attempt. I refactored your changes and remove some duplicates. https://github.com/DavidWiesner/cordova-plugin-camera/commit/91392a498f25b9053abc9f49d8eb0234451ccf10

**Comment by DavidWiesner** [comment]
If you access the photo library for the metadata it will ask for permission in a async manner. This will happen after you query for metadata. So there will be no metadata on the very first time you query them. You have to ask for permission first in a blocking way before query for metadata.

**Comment by evripidesk** [comment]
this still not working

**Comment by ryaa** [comment]
> this still not working

Can you please provide more details? What iOS version? Detailed steps? Did you install from my fork?

**Comment by evripidesk** [comment]
Yes of course, iOS 13.2.2 
```
const options: CameraOptions = {
                    quality: 100,
                    sourceType : this.camera.PictureSourceType.PHOTOLIBRARY,
                    destinationType: this.camera.DestinationType.FILE_URI,
                    encodingType: this.camera.EncodingType.JPEG,
                    mediaType: this.camera.MediaType.PICTURE,
                    saveToPhotoAlbum: false,
                    allowEdit: true,
                    //correctOrientation: true
                  } 
....
exif.getData(  file1 , function(error) {
                              if (error) {
                                console.log(error)
                              }
                              var allMetaData = EXIF.getAllTags(this);
                              console.log('ALL TAGS - ', allMetaData)
                      
                              let lng = EXIF.getTag(this, 'GPSLongitude') || null
                              let lat = EXIF.getTag(this, 'GPSLatitude') || null
                      
                              console.log('LNG - ', lng)
                              console.log('LAT - ', lat)
                          })
                          }
```
config.xml
```<preference name="CameraUsesGeolocation" value="true" />```
I installed on Ionic from this https://ionicframework.com/docs/native/camera/, on android is working

**Comment by ryaa** [comment]
> I installed on Ionic from this https://ionicframework.com/docs/native/camera/, on android is working

That's the problem. The fix is only in my forked repo and has not been merged/released in the camera repository. Please try to install the plugin from my repo and see if this makes any difference.

**Comment by evripidesk** [comment]
how can i install from your repo on ionic?

**Comment by ryaa** [comment]
> how can i install from your repo on ionic?

1) first remove the existing camera plugin
```
cordova plugin rm cordova-plugin-camera
```
or for ionic
```
ionic cordova plugin rm cordova-plugin-camera
```
2) add the version from my repo by running
```
cordova plugin add https://github.com/ryaa/cordova-plugin-camera.git
```
or for ionic
```
ionic cordova plugin add https://github.com/ryaa/cordova-plugin-camera.git
```

Let me know if the problem is fixed after the above

**Comment by evripidesk** [comment]
thank you! perfect is working!! :)

**Comment by DavidWiesner** [comment]
It is still not solved to get the exif on the very first call

**Comment by DavidWiesner** [comment]
@ryaa I added the permission request with my refactoring in this commit https://github.com/DavidWiesner/cordova-plugin-camera/commit/62c55c00d5a9cafe878e415baffb02a04d5828d5

**Comment by danielehrhardt** [comment]
> > how can i install from your repo on ionic?
> 
> 1. first remove the existing camera plugin
> 
> ```
> cordova plugin rm cordova-plugin-camera
> ```
> 
> or for ionic
> 
> ```
> ionic cordova plugin rm cordova-plugin-camera
> ```
> 
> 1. add the version from my repo by running
> 
> ```
> cordova plugin add https://github.com/ryaa/cordova-plugin-camera.git
> ```
> 
> or for ionic
> 
> ```
> ionic cordova plugin add https://github.com/ryaa/cordova-plugin-camera.git
> ```
> 
> Let me know if the problem is fixed after the above

Solved my Problem

**Comment by patrickbussmann** [comment]
Can someone merge this please?
It solves problems and waits since weeks 🙂

@apache @stevengill @alsorokin @agrieve @jcesarmobile @purplecabbage @infil00p @shazron @muratsu @ldeluca

Thanks in Advance!

**Comment by incentfit** [comment]
I forked ryaa's version, added the fix from DavidWiesner, then fixed a bug so that gallery permissions are not requested when in camera mode. Should be solid to use while we are waiting for these fixes to be applied to this main repo.
https://github.com/incentfit/cordova-plugin-camera

**Comment by oudj001** [comment]
Hi @incentfit, how do I get the exif data from the file? Thanks.

This is my code:

> const options: CameraOptions = {
>         quality: 80,
>         targetWidth: 600,
>         targetHeight: 600,
>         allowEdit: false,
>         destinationType: this.camera.DestinationType.FILE_URI,
>         encodingType: this.camera.EncodingType.JPEG,
>         mediaType: this.camera.MediaType.ALLMEDIA,
>         sourceType: this.camera.PictureSourceType.PHOTOLIBRARY,
>         correctOrientation: true
>       };
> 
>       const originalPhoto = await this.camera.getPicture(options);

**Comment by ryaa** [comment]
> @ryaa I added the permission request with my refactoring in this commit [DavidWiesner@62c55c0](https://github.com/DavidWiesner/cordova-plugin-camera/commit/62c55c00d5a9cafe878e415baffb02a04d5828d5)

I integrated the permission request related change https://github.com/ryaa/cordova-plugin-camera/commit/4a5538a97fa959f0dd8a6efe5892819a5c1497be

Thank you for the improvement!

**Comment by ryaa** [comment]
> I forked ryaa's version, added the fix from DavidWiesner, then fixed a bug so that gallery permissions are not requested when in camera mode. Should be solid to use while we are waiting for these fixes to be applied to this main repo.
> https://github.com/incentfit/cordova-plugin-camera

requestPhotoPermissions returns bool which does not seem to be used. Is this intended?

**Comment by SumeetHindinkeri** [comment]
Does current cordova-plugin-camera 4.1.0 supports to get exif data from an image when destination type is File_URI?

**Comment by DavidWiesner** [comment]
@ryaa there is no need to get this permission in camera mode. In camera mode you always get the exif from the image itself

**Comment by sc0ttdav3y** [comment]
First, thanks so much to @ryaa, @incentfit and others for all your effort on this PR. This particular fix is tremendously important for Cordova, as I imagine the bulk of Cordova apps are data capture style apps with forms, photos, etc, and for one let down a customer big-time from this issue. I hope those with the power to merge this in can treat this the urgency it deserves, to prevent others suffering the same fate as I.

Anyway, onto positive matters. I've done extensive real device testing — **here's what works (and doesn't work) for me**. 

**Step one: install incentfit's fork**

Install incentfit's fork (at this commit https://github.com/incentfit/cordova-plugin-camera/commit/e52290a5d9705b186a7b190c55a607d68f9dd6ed):

```
cordova plugin remove cordova-plugin-camera
cordova plugin add https://github.com/incentfit/cordova-plugin-camera.git 
``` 

**Step two: ensure your `config.xml` has `CameraUsesGeolocation` .**

```
<platform name="ios">
        <preference name="CameraUsesGeolocation" value="true" />
</platform>
```

If this is off, I verified iOS will not record the location into the image.

**Step three: use this configuration when launching the camera**

- `quality`: tested okay with `75`; also works when undefined
- `destinationType`: tested okay with `Camera.DestinationType.FILE_URI` (cc @SumeetHindinkeri)
- `sourceType`: works with both `Camera.PictureSourceType.CAMERA` and `Camera.PictureSourceType.PHOTOLIBRARY`
- `targetHeight` and `targetWidth`: tested okay with `1920`; also works when undefined
- `saveToPhotoAlbum`: tested okay with `true` and undefined

These need special care:

- `allowEdit`: in my device testing, this must be `false` to work on Android, must be `true` to work on Windows, and seems to work either way with no observable difference for iOS. I'm guessing nobody cares about Windows now, so set to `false`.
- `correctOrientation`: must be set to `false`, otherwise Camera.PictureSourceType.PHOTOLIBRARY still loses exif data on iOS, even with @ryaa and @incentfit's work.

Tested on iPhone 11 on iOS 13.5.1 and a Lenovo tablet running Android 8.1.0.

Thanks again to all those that are supporting this plugin, and reach out if you need further device testing.

**Comment by SumeetHindinkeri** [comment]
@sc0ttdav3y  I followed your comment thanks for it but I am not able to capture image through it. Getting following error everytime:
CGImageSource was created with data size: 149657 - current size is only: 0

**Comment by sc0ttdav3y** [comment]
@SumeetHindinkeri I didn't get that error myself. Since my post a month ago, I actually switched to using @ryaa's fork (https://github.com/ryaa/cordova-plugin-camera). I can't recall exactly what I found wrong that made me switch, but this is where I landed on my project and it's working. I've got my app into production. Android 5.1.1 has problems, and the first photo taken on Android misses metadata, but it looks to be the best we've got right now.

**Comment by SumeetHindinkeri** [comment]
@sc0ttdav3y thanks for you reply. I tried with @ryaa's fork just now. Working fine to capture picture but metadata goes missing. Checked with iphone X.

**Comment by Jack-imagic** [comment]
When will @ryaa PR be approved ? 
I'd love to have the EXIF data also from images from the camera roll. 
I don't want to always have to edit and fork plugins from different places and not be able to ever update them again..

How do you guys deal with that problem? (you need a fix that is only available on someones fork) on a production active application?

**Comment by ryaa** [comment]
Added some changes to handle iOS 14 Photo permissions changes - see https://github.com/ryaa/cordova-plugin-camera/commit/4208f81bc27bbcc19fe89a785d98a195f8a5e658

**Comment by codeconsole** [comment]
@ryaa Seems like the android version has already been fixed?  can you submit a pull request with just the IOS fix?  Maybe that will expedite a merge?

**Comment by ryaa** [comment]
> Maybe that will expedite a merge?

I don't think that it will make any difference..

**Comment by codeconsole** [comment]
To simplify things, I created a pull request with just the ios changes from @ryaa 
https://github.com/apache/cordova-plugin-camera/pull/712
Can we please get this pull request merged?

**Comment by erisu** [comment]
closed by #712

**Pull request closed without merging**
