### PR TITLE
CB-11232 Appium tests: fixed element tapping on iOS 9

### PR DESCRIPTION
**Pull request by alsorokin**
https://issues.apache.org/jira/browse/CB-11232

### CODE REVIEW

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Dashboard** - http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1/

**Results**
1. [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=windows-slave,platformName=windows-8.1-store/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=windows-slave,platformName=windows-8.1-store/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=windows-slave,platformName=windows-8.1-store/testReport/) - [Build Artifacts]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=windows-slave,platformName=windows-8.1-store/artifact/)
2. [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//80/label=windows-slave,platformName=windows-10-store/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=windows-slave,platformName=windows-10-store/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=windows-slave,platformName=windows-10-store/testReport/) - [Build Artifacts]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=windows-slave,platformName=windows-10-store/artifact/)
3. [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=windows-slave,platformName=windows-8.1-phone/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=windows-slave,platformName=windows-8.1-phone/) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=windows-slave,platformName=windows-8.1-phone/testReport/) - [Build Artifacts]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=windows-slave,platformName=windows-8.1-phone/artifact/)
4. [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=mac-slave,platformName=ios/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=mac-slave,platformName=ios/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=mac-slave,platformName=ios/testReport/) - [Build Artifacts]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=mac-slave,platformName=ios/artifact/)
5. [Android Mac]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=mac-slave,platformName=android/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=mac-slave,platformName=android/) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=mac-slave,platformName=android/testReport/) - [Build Artifacts]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=mac-slave,platformName=android/artifact/)
6. [Android Windows]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=windows-slave,platformName=android/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=windows-slave,platformName=android/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=windows-slave,platformName=android/testReport/) - [Build Artifacts]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/1//label=windows-slave,platformName=android/artifact/)

**Comment by alsorokin** [comment]
Restarted the CI check. It passed this time.

**Comment by cordova-qa** [comment]
Cordova CI Build has one or more failures. 

**Dashboard** - http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2/


**Results**
1. [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=windows-slave,platformName=windows-8.1-store/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=windows-slave,platformName=windows-8.1-store/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=windows-slave,platformName=windows-8.1-store/testReport/) - [Device Logs]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=windows-slave,platformName=windows-8.1-store/artifact/)
2. [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=windows-slave,platformName=windows-10-store/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=windows-slave,platformName=windows-10-store/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=windows-slave,platformName=windows-10-store/testReport/) - [Device Logs]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=windows-slave,platformName=windows-10-store/artifact/)
3. [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=windows-slave,platformName=windows-8.1-phone/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=windows-slave,platformName=windows-8.1-phone/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=windows-slave,platformName=windows-8.1-phone/testReport/) - [Device Logs]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=windows-slave,platformName=windows-8.1-phone/artifact/)
4. [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=mac-slave,platformName=ios/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=mac-slave,platformName=ios/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=mac-slave,platformName=ios/testReport/) - [Build Artifacts]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=mac-slave,platformName=ios/artifact/)
5. [Android Mac]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=mac-slave,platformName=android/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=mac-slave,platformName=android/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=mac-slave,platformName=android/testReport/) - [Build Artifacts]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=mac-slave,platformName=android/artifact/)
6. [Android Windows]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=windows-slave,platformName=android/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=windows-slave,platformName=android/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=windows-slave,platformName=android/testReport/) - [Device Logs]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/2//label=windows-slave,platformName=android/artifact/)

**Comment by sarangan12** [comment]
Let there be tests

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully. 

**Dashboard** - http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7/

**Results**
1. [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=windows-slave,platformName=windows-8.1-store/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=windows-slave,platformName=windows-8.1-store/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=windows-slave,platformName=windows-8.1-store/testReport/) - [Device Logs]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=windows-slave,platformName=windows-8.1-store/artifact/)
2. [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=windows-slave,platformName=windows-10-store/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=windows-slave,platformName=windows-10-store/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=windows-slave,platformName=windows-10-store/testReport/) - [Device Logs]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=windows-slave,platformName=windows-10-store/artifact/)
3. [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=windows-slave,platformName=windows-8.1-phone/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=windows-slave,platformName=windows-8.1-phone/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=windows-slave,platformName=windows-8.1-phone/testReport/) - [Device Logs]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=windows-slave,platformName=windows-8.1-phone/artifact/)
4. [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=mac-slave,platformName=ios/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=mac-slave,platformName=ios/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=mac-slave,platformName=ios/testReport/) - [Build Artifacts]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=mac-slave,platformName=ios/artifact/)
5. [Android Mac]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=mac-slave,platformName=android/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=mac-slave,platformName=android/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=mac-slave,platformName=android/testReport/) - [Build Artifacts]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=mac-slave,platformName=android/artifact/)
6. [Android Windows]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=windows-slave,platformName=android/) - [Console Output]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=windows-slave,platformName=android/console) - [Test Results]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=windows-slave,platformName=android/testReport/) - [Device Logs]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/7//label=windows-slave,platformName=android/artifact/)

**Comment by sarangan12** [comment]
Let there be tests

**Comment by cordova-qa** [comment]
Cordova CI Build has completed successfully. 

**Commit**     - [Link](https://github.com/apache/cordova-plugin-camera/pull/214/commits/d0ec4893071c9dc92e7978df953727633a7620ee)
**Dashboard** - [Link](http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8/)

| Builder Name  | Console Output | Test Report | Device Logs  |
|     :---:     |     :---:      |   :---:     |     :---:    |
| [Windows 8.1 Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=windows-slave,platformName=windows-8.1-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=windows-slave,platformName=windows-8.1-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=windows-slave,platformName=windows-8.1-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=windows-slave,platformName=windows-8.1-store/artifact/) |
| [Windows 10  Store]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=windows-slave,platformName=windows-10-store/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=windows-slave,platformName=windows-10-store/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=windows-slave,platformName=windows-10-store/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=windows-slave,platformName=windows-10-store/artifact/) |
| [Windows 8.1 Phone]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=windows-slave,platformName=windows-8.1-phone/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=windows-slave,platformName=windows-8.1-phone/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=windows-slave,platformName=windows-8.1-phone/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=windows-slave,platformName=windows-8.1-phone/artifact/) |
| [iOS]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=mac-slave,platformName=ios/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=mac-slave,platformName=ios/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=mac-slave,platformName=ios/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=mac-slave,platformName=ios/artifact/) |
| [Android Mac]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=mac-slave,platformName=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=mac-slave,platformName=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=mac-slave,platformName=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=mac-slave,platformName=android/artifact/) |
| [Android Windows]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=windows-slave,platformName=android/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=windows-slave,platformName=android/console) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=windows-slave,platformName=android/testReport/) | [Link]( http://cordova-ci.cloudapp.net:8080/job/cordova-plugin-camera/8//label=windows-slave,platformName=android/artifact/) |

**Comment by nikhilkh** [comment]
LGTM

**Pull request closed without merging**
